modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ldshadowlady5/things/issues"
[[mods]]
modId="lizziesthings"
version="${file.jarVersion}"
displayName="Lizzie's Things"
displayURL="https://github.com/ldshadowlady5/things"
authors="LDShadowLady, pau101"
description="Adds a few things"
[[dependencies.lizziesthings]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lizziesthings]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
